language: csharp
os:
  - osx
  - linux

# Ubuntu 14.04
sudo: required
dist: trusty

# OS X 10.12
osx_image: xcode9.2

mono:
  - 4.4.2

dotnet: 2.1.4

before_install:
  - git fetch --unshallow # Travis always does a shallow clone, but GitVersion needs the full history including branches and tags
  - git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
  - git fetch origin

script:
  - ./build.sh

cache:
  directories:
    - .packages
    - tools/Addins
    - tools/gitreleasemanager
    - tools/GitVersion.CommandLine